name: Alexa Shopping List Spanish Sync
version: "0.1"
slug: alexa_shopping_list
description: Alexa Shopping List Spanish synchronisation server
url: "https://github.com/Carlosgonal/home-assistant-alexa-shopping-list-spanish"
arch:
  - aarch64
  - amd64
image: "carlosgonal/ha-alexa-shopping-list-spanish-sync"
startup: "services"
ports:
  4000/tcp: 4000
map:
  - type: data
    path: "/config"
    read_only: false